INSERT INTO movie (title, slug, description, duration_minutes, language, genre, release_date, poster_url, censor_rating, trailer_url, created_at) VALUES
('Big Buck Bunny', 'big-buck-bunny', 'A gentle giant rabbit is bullied by three mischievous rodents until he decides enough is enough and turns the tables in this beloved animated comedy.', 118, 'English', 'Comedy', CURRENT_DATE - INTERVAL 12 DAY, 'https://picsum.photos/seed/big-buck-bunny/400/600', 'U', 'https://www.youtube.com/watch?v=YE7VzlLtp-4', NOW()),
('Sintel', 'sintel', 'A lone warrior named Sintel searches the world for a baby dragon she raised and lost, in this epic tale of loss and reunion.', 124, 'English', 'Fantasy', CURRENT_DATE - INTERVAL 9 DAY, 'https://picsum.photos/seed/sintel/400/600', 'UA', 'https://www.youtube.com/watch?v=eRsGyueVLvQ', NOW()),
('Tears of Steel', 'tears-of-steel', 'In a future Amsterdam ravaged by war with robots, a group of warriors and scientists gather to make a last stand and try to change the past.', 132, 'English', 'Sci-Fi', CURRENT_DATE - INTERVAL 6 DAY, 'https://picsum.photos/seed/tears-of-steel/400/600', 'UA', 'https://www.youtube.com/watch?v=R6MlUcmOul8', NOW()),
('Cosmos Laundromat', 'cosmos-laundromat', 'A suicidal flying sheep gets a second chance at life when a mysterious salesman offers him a new body -- and a bizarre adventure across the cosmos.', 115, 'English', 'Sci-Fi Comedy', CURRENT_DATE - INTERVAL 4 DAY, 'https://picsum.photos/seed/cosmos-laundromat/400/600', 'UA', 'https://www.youtube.com/watch?v=Y-rmzh0PI3c', NOW()),
('Spring', 'spring', 'A shepherdess and her dog uncover a nature spirit who must sacrifice everything to end an eternal winter, in this lush tale of the seasons.', 108, 'English', 'Fantasy', CURRENT_DATE - INTERVAL 3 DAY, 'https://picsum.photos/seed/spring/400/600', 'U', 'https://www.youtube.com/watch?v=WhWc3b3KhnY', NOW()),
('Elephants Dream', 'elephants-dream', 'Two strange companions journey through a surreal, machine-filled world in this landmark film -- the first ever fully open-source animated feature.', 121, 'English', 'Sci-Fi', CURRENT_DATE - INTERVAL 2 DAY, 'https://picsum.photos/seed/elephants-dream/400/600', 'UA', 'https://www.youtube.com/watch?v=TLkA0RELQ1g', NOW()),
('Caminandes: Llama Drama', 'caminandes-llama-drama', 'A llama''s journey home hits a snag when a stubborn armadillo blocks the road, sparking a comic showdown in the Andes.', 106, 'English', 'Comedy', CURRENT_DATE - INTERVAL 1 DAY, 'https://picsum.photos/seed/caminandes/400/600', 'U', 'https://www.youtube.com/watch?v=Ehcmk3NJneI', NOW()),
('Charge', 'charge', 'In an energy-scarce dystopia, a desperate old man breaks into a battery factory and finds himself face-to-face with a lethal security droid.', 128, 'English', 'Action', CURRENT_DATE, 'https://picsum.photos/seed/charge/400/600', 'UA', 'https://www.youtube.com/watch?v=UXqq0ZvbOnk', NOW());
