CREATE TABLE blog_post (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL,
    excerpt TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    published_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB;

CREATE INDEX idx_blog_post_category ON blog_post (category, published_at);

INSERT INTO blog_post (title, slug, category, excerpt, content, image_url, published_at, created_at) VALUES
('5 Stadium Rituals Every Kabaddi Fan Should Know', 'stadium-rituals-every-kabaddi-fan-should-know', 'SPORTS',
 'From the pre-raid chant to the tie-break huddle, here''s what to watch for beyond the scoreboard.',
 'Pro Kabaddi crowds have their own language of chants, claps, and superstitions. In this piece we walk through the raid-side chant that builds before every "do-or-die" raid, the bench rituals teams use to settle nerves before a tie-break, and why the home crowd''s stomping rhythm can genuinely rattle a raider. Whether you''re watching your first match live or your fiftieth, knowing these cues turns a good night out into a great one.',
 'https://picsum.photos/seed/blog-kabaddi/600/400', NOW() - INTERVAL 2 DAY, NOW()),
('Courtside Etiquette: A First-Timer''s Guide to Live Sports Screenings', 'courtside-etiquette-first-timers-guide', 'SPORTS',
 'Screening nights aren''t quite like watching at home. Here''s how to enjoy the atmosphere without missing the action.',
 'Big-screen sports nights blend the energy of a stadium with the comfort of assigned seating, and that mix has its own unwritten rules. We cover when it''s fine to cheer loudly versus when the room goes quiet for a close call, how early to arrive for a good view of the fan-zone activities, and why sitting near the aisle is the local regulars'' favorite trick for quick snack runs between overs.',
 'https://picsum.photos/seed/blog-screening/600/400', NOW() - INTERVAL 6 DAY, NOW()),
('The Rise of Celebrity Cricket Leagues in India', 'rise-of-celebrity-cricket-leagues-in-india', 'SPORTS',
 'What started as charity exhibition matches has become one of the most-attended screening events of the year.',
 'Celebrity Cricket League finals now sell out screening halls faster than most regular-season matches. We trace how these charity-driven exhibition games grew a dedicated following, why fans show up as much for the fan-zone giveaways as for the cricket itself, and what to expect if you''re catching your first CCL final on the big screen this season.',
 'https://picsum.photos/seed/blog-ccl/600/400', NOW() - INTERVAL 10 DAY, NOW()),
('Pottery for Beginners: What to Expect at Your First Workshop', 'pottery-for-beginners-first-workshop', 'ACTIVITY',
 'No experience needed — here''s what actually happens at a hands-on pottery-and-wine session.',
 'If you''ve never touched a pottery wheel, walking into a studio session can feel intimidating. It isn''t. Most beginner workshops spend the first fifteen minutes just getting you comfortable with wet clay before anyone touches a wheel, instructors expect (and plan for) lopsided first bowls, and the wine pairing is timed for the drying breaks, not the messy parts. Here''s a realistic walkthrough of a two-hour session, from apron to kiln.',
 'https://picsum.photos/seed/blog-pottery/600/400', NOW() - INTERVAL 3 DAY, NOW()),
('How to Get the Most Out of a Startup Founders Meetup', 'get-most-out-of-founders-meetup', 'ACTIVITY',
 'Lightning talks are the easy part. The real value is in the ten minutes before and after.',
 'Founder meetups pack a lot into one evening, and the talks themselves are rarely where the best connections happen. We share a few practical habits from regular attendees: arrive during the networking window rather than right at the first talk, prepare a one-sentence version of what you''re building, and follow up with new contacts within 48 hours while the conversation is still fresh.',
 'https://picsum.photos/seed/blog-founders/600/400', NOW() - INTERVAL 8 DAY, NOW()),
('Modern Art, Explained: A Guide to Reading a Gallery Walkthrough', 'guide-to-reading-a-gallery-walkthrough', 'ACTIVITY',
 'Guided walkthroughs give you more than a room full of paintings — here''s how to make the most of one.',
 'A curated gallery walkthrough is designed to give context you''d otherwise miss browsing alone: why a piece was placed where it is, what movement it responds to, and what the artist was reacting to at the time. We put together a short primer on the kinds of questions worth asking your guide, and why the last room in most contemporary showcases is usually the one worth lingering in.',
 'https://picsum.photos/seed/blog-art/600/400', NOW() - INTERVAL 12 DAY, NOW()),
('Behind the Scenes: How a Comedy Special Gets Its Final Cut', 'how-a-comedy-special-gets-its-final-cut', 'EVENTS',
 'The hour you see on stage is often the fifth or sixth version of the set. Here''s how comics get there.',
 'Stand-up specials that tour cinema halls have usually been through months of smaller club sets first. We spoke to circuit regulars about how a joke gets cut, rewritten, or moved to the closer slot based on nothing but crowd reaction, and why the version you see on a big tour is rarely the first draft — or even the tenth.',
 'https://picsum.photos/seed/blog-comedy/600/400', NOW() - INTERVAL 4 DAY, NOW()),
('A Concertgoer''s Guide to Getting the Best Seat', 'concertgoers-guide-to-best-seat', 'EVENTS',
 'Not all seats are created equal — here''s how to pick yours based on the kind of show you''re going to.',
 'The best seat for a bass-heavy electronic set is not the best seat for an acoustic singer-songwriter show. We break down how sound travels in typical venue layouts, why being close to the stage isn''t always the win it seems, and a few seating-chart tricks regulars use to land good spots even for shows that sell out fast.',
 'https://picsum.photos/seed/blog-concert/600/400', NOW() - INTERVAL 15 DAY, NOW()),
('Why Live Events Are Booking Out Faster Than Ever', 'why-live-events-are-booking-out-faster', 'EVENTS',
 'A look at what''s driving demand for comedy, music, and exhibition events across Indian cities.',
 'Ticket sales for live comedy, music, and exhibition events have climbed sharply over the last few years. We look at a few forces behind it: more touring artists adding second and third city dates, venues investing in better sound and seating, and audiences increasingly treating a live show as the plan for the night rather than an add-on to it.',
 'https://picsum.photos/seed/blog-live-events/600/400', NOW() - INTERVAL 1 DAY, NOW());
